### ISSUE TITLE
Support parsing multiple modules per package.

### ISSUE THREAD

**Issue by Raynos** [jonschlinkert/lint-deps#8]
I get the following output:

```
    · test/index.js ✔
    · test/lib/hammock-request.js ✖  (hammock/request, hammock/response)
    · test/router.js ✔
    · test/server.js ✖  (hammock/request, hammock/response)
    · typed-request.js ✔

  16 unused packages found: 'coveralls', 'hammock', 'istanbul', 'jscs', 'jshint', 'opn', 'pre-commit', 'airlock', 'error', 'interset', 'jayschema', 'jayschema-error-messages', 'json-schema-filter', 'request', 'safe-json-parse', 'send-data'

  This tool doesn't remove dependencies, you'll have 
  to do that manually.
  ---

  9 missing packages found:   'console', 'error/io', 'error/typed', 
  'hammock/request', 'hammock/response', 
  'interset/difference', 'safe-json-parse/tuple', 
  'send-data/error', 'send-data/json'
```

Importing modules out of packages is valid and should be supported by your parser. i.e. support `require('error/io')

It also looks like your unused package analysis misses a few features

 - check whether a package is used as a binary in `npm run` scripts.

**Comment by jonschlinkert** [comment]
> Importing modules out of packages is valid and should be supported by your parser

agreed. this has caused me issues more than a few times. 

> It also looks like your unused package analysis misses a few features

also agreed. the logic for unused packages just needs to be refactored. I'll stars working on something. thanks for the feedback

**Comment by jonschlinkert** [comment]
I created another issue for `npm run` scripts. Any thoughts on a reliable way to parse those? 

Here's what I'm thinking:

- loop over the keys on `scripts`
- remove obvious cruft from the values
- turn them into glob patterns or regex to match against deps listed in `devDependencies` or `dependencies`
